# Generated by Django 2.2.1 on 2019-05-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190522_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
