# Generated by Django 2.2.1 on 2019-05-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190522_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(blank=True, default='1', max_length=100),
            preserve_default=False,
        ),
    ]
